services:
  - type: static
    name: taita-frontend
    env: node
    buildCommand: npm install && npm run generate
    publishDir: dist
    envVars:
      - key: NODE_ENV
        value: production
      - key: NUXT_PUBLIC_API_BASE_URL
        value: https://taita-api.onrender.com/api
    autoDeploy: true